### ISSUE TITLE
Release 5.1.0

### ISSUE THREAD

**Issue by ryush00** [mongoid/mongoid-geospatial#60]
I found out [rubygems.org mongoid-geospatial](https://rubygems.org/gems/mongoid-geospatial/) is stuck on 5.0.0. I think It should be updated to newer version. thanks.

**Comment by dblock** [comment]
5.1.0 doesn't seem to have have any changes according to https://github.com/mongoid/mongoid-geospatial/blob/master/CHANGELOG.md, or am I missing something?

**Comment by ryush00** [comment]
Hmm.. I just want to use this gem with mongoid 6. But I got an error.

Is it not support mongoid 6 yet?

**Comment by dblock** [comment]
AFAIK 5.0.0 should work correctly with Mongoid 6, what's the error? Does it go away with using HEAD?

**Comment by ryush00** [comment]
I did that with HEAD and it also not working with `NameError: uninitialized constant Mongoid::Geospatial` error.

I'm using rails 5.1.3 and mongoid 6.2.0.

**Comment by dblock** [comment]
That sounds odd, does adding an explicit `require 'mongoid/geospacial'` fix the problem?

**Comment by ryush00** [comment]
`require 'mongoid/geospacial'` to Gemfile?

**Comment by dblock** [comment]
No, in your code. In a rails app somewhere like in `config/initializers`. 

I assume you added `gem 'geospacial'` to Gemfile and ran `bundle install`, then restarted Rails.

**Comment by ryush00** [comment]
```
ryush00@dev:~/app$ bundle
...
Using mongoid 6.2.0
...
Using mongoid-geospatial 5.0.0 from https://github.com/mongoid/mongoid-geospatial.git (at master@9d25a5a)
...
Using rails 5.1.3
...
Bundle complete! 24 Gemfile dependencies, 96 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
The latest bundler is 1.15.3, but you are currently running 1.15.1.
To update, run `gem install bundler`

ryush00@dev:~/app$ rails s
/home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- mongoid/geospacial (LoadError)
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
        from /home/ryush00/app/config/application.rb:18:in `<top (required)>'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.3/lib/rails/commands/server/server_command.rb:129:in `require'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.3/lib/rails/commands/server/server_command.rb:129:in `block in perform'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.3/lib/rails/commands/server/server_command.rb:126:in `tap'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.3/lib/rails/commands/server/server_command.rb:126:in `perform'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.3/lib/rails/command/base.rb:63:in `perform'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.3/lib/rails/command.rb:44:in `invoke'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.3/lib/rails/commands.rb:16:in `<top (required)>'
        from /home/ryush00/app/bin/rails:9:in `require'
        from /home/ryush00/app/bin/rails:9:in `<top (required)>'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/ryush00/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/ryush00/app/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

It's really odd..

I'm going to find another way to use geospatial. Thanks.

**Comment by dblock** [comment]
@ryush00 Can you put up a plain Rails project with this on Github that reproduces the problem?

**Comment by dblock** [comment]
Oh you mispelled `geospatial`, it's with a `t`.

**Comment by ryush00** [comment]
Oh! Thank you. lol 👍 
My mistake
